blank_issues_enabled: false
contact_links:
  - name: Get help
    url: https://github.com/joe-bell/cva/discussions/new?category=q-a
    about: Ask the community for help
  - name: Ideas
    url: https://github.com/joe-bell/cva/discussions/new?category=ideas
    about: Share ideas for new features
  - name: Feedback
    url: https://github.com/joe-bell/cva/discussions/new?category=feedback
    about: Feedback that isn't necessarily related to new ideas
